import Header from '@/components/header/Header';
import './globals.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Restaurant Reservation Service',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <div className='min-h-screen min-w-full'>
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
