import '../../globals.scss';
import type { Metadata } from 'next';
import RestaurantName from '../components/restaurant-name/RestaurantName';

export const metadata: Metadata = {
  title: 'Restaurant Reservation Service',
  description: 'Generated by create next app',
};

export default function RestaurantLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <RestaurantName />
      {children}
    </>
  );
}
